### PR TITLE
Add PasswordPolicyControl

### PR DESCRIPTION
**Pull request by its-sami**
I've done the steps outlined in https://github.com/ldapjs/node-ldapjs/issues/946#issuecomment-1741760847 but haven't linked to the issue as it's closed. Let me know if there's anything else I should do!

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
Good work. Thank you for following the defined organization.

I have one question, do you think it would be appropriate to add a mechanism for error code lookup? We do it in:

https://github.com/ldapjs/controls/blob/9718b85dc8eae4522e5d879a603a13422d6e245a/lib/controls/server-side-sorting-response-control.js#L9-L27

https://github.com/ldapjs/controls/blob/9718b85dc8eae4522e5d879a603a13422d6e245a/lib/controls/server-side-sorting-response-control.js#L44-L49

**Comment by its-sami** [comment]
Thanks, I had avoided a lookup like that as the error codes in the control don't match the result codes defined in the protocol. Also no mapping is defined in the similar case:

https://github.com/ldapjs/controls/blob/9718b85dc8eae4522e5d879a603a13422d6e245a/lib/controls/entry-change-notification-control.js#L8-L14

I'd be happy to create some kind of mapping though.

**Comment by jsumners** [comment]
That's fair.

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Pull request merged**
